;Archivo de configuración

[paths]

pathAutoload = ./vendor/phpunit/PHPUnit/Autoload.php
pathPear = /usr/share/php

;Dependencias

pathPhpunit = ./vendor/phpunit/ 
pathDbunit = ./vendor/dbunit/
pathCodeCoverage = ./vendor/php-code-coverage/
pathFileIterator = ./vendor/php-file-iterator/
pathInvoker = ./vendor/php-invoker/
pathTextTemplate = ./vendor/php-text-template/
pathTimer = ./vendor/php-timer
pathTokenStream = ./vendor/php-token-stream
pathMockObjects = ./vendor/phpunit-mock-objects/
pathSelenium = ./vendor/phpunit-selenium/
pathStory = ./vendor/phpunit-story/
pathVersion = ./vendor/version
