[dependencies]

pathPhpunit = vendor/phpunit/phpunit/ 
pathDbunit = vendor/phpunit/dbunit/
pathCodeCoverage = vendor/phpunit/php-code-coverage/
pathFileIterator = vendor/phpunit/php-file-iterator/
pathInvoker = vendor/phpunit/php-invoker/
pathTextTemplate = vendor/phpunit/php-text-template/
pathTimer = vendor/phpunit/php-timer
pathTokenStream = vendor/phpunit/php-token-stream
pathMockObjects = vendor/phpunit/phpunit-mock-objects/
pathSelenium = vendor/phpunit/phpunit-selenium/
pathStory = vendor/phpunit/phpunit-story/
pathVersion = vendor/phpunit/version
pathSymfony = vendor/symfony/yaml

[paths]

serverDirectory = /opt/lampp/
pubDirectory = /opt/lampp/htdocs/
runService = /opt/lampp/lampp

